### ISSUE TITLE
Convert HTML files, not just XHTML

### ISSUE THREAD

**Issue by itsupera** [haoxuany/furiganalize-epub#1]
Hi !

I tried to "furiganalize" a book converted from AZW3 to EPUB, but it did not work because archive files had the html extension instead of xhtml.
It worked after patching the code to convert html files instead of xhtml.

In general, don't we want to convert both html and xhtml ?
Or should a valid EPUB only have xhtml files ?

Thanks for your great work !

**Comment by haoxuany** [comment]
Sorry for the late reply, you might be able to tell that this project isn't my priority at the moment, since I'm working on https://github.com/haoxuany/jpndrill at the moment which is closer to my current use case of japanese learning.
I've merged your commit in https://github.com/haoxuany/furiganalize-epub/pull/2 . Thank you!

**Comment by itsupera** [comment]
No problem. Actually in the mean time I created a similar project and improved on the furigana detection + added many other options such as Anki export: https://github.com/itsupera/furiganalyse
Looking forward for your new project, cheers !
